### ISSUE TITLE
Where is the temporal reasoning dataset?

### ISSUE THREAD

**Issue by yasNing** [zhaochen0110/Timo#1]
I cannot find the temporal reasoning dataset used for benchmarking in this paper.

**Comment by zhaochen0110** [comment]
Hi,

The dataset has been uploaded to Hugging Face. You can access it via the following link: 
- **Default pure-time datasets:** https://huggingface.co/datasets/Warrieryes/TRAM-Temporal
- **Temporal preference pairs generated by LLaMA-7B:** https://huggingface.co/datasets/Warrieryes/TRAM-Temporal-DPO-7B
- **Temporal preference pairs generated by LLaMA-14B:** https://huggingface.co/datasets/Warrieryes/TRAM-Temporal-DPO-13B

Moreover, you can find all TRAM datasets at https://github.com/EternityYW/TRAM-Benchmark.
